### Indice
GET http://localhost:65000

### Lista de alumnas
GET http://localhost:65000/students

### Lista de profesores
GET http://localhost:65000/teachers

### Agregar nueva alumna
POST http://localhost:65000/student

{
  "nombre": "Carolina",
  "curso": "Backend"
}

### Prueba 
GET http://localhost:1234/asdasd

### Agregar nuevo profesor
POST http://localhost:1234/students

{
  "nombre": "Luisa",
  "curso": "Backend"
}